services:
  # Load Balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - makeAWish-service1
      - makeAWish-service2

  # MakeAWish-Microservice Instance 1
  makeAWish-service1:
    build:
      context: ./makeAWish-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/xmas_wishes

  # MakeAWish-Microservice Instance 2
  makeAWish-service2:
    build:
      context: ./makeAWish-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/xmas_wishes

  # MognoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: